# Supported Instruments

The goFlux package supports import functions for 22+ instruments from multiple manufacturers.

| Function | Instrument | Manufacturer | Type | Import Method |
|----------|-----------|--------------|------|----------------|
| [`import.DX4015`](#import.dx4015) | Gasmet DX4015 | Gasmet | Single or batch |
| [`import.EGM5`](#import.egm5) | PP-Systems EGM-5 | PP-Systems | Single or batch |
| [`import.eosMX12`](#import.eosmx12) | eosMX12 | Eosense | Single or batch |
| [`import.G2201i`](#import.g2201i) | Picarro G2201-i | Picarro | Single or batch |
| [`import.G2508`](#import.g2508) | Picarro G2508 | Picarro | Single or batch |
| [`import.G4301`](#import.g4301) | Picarro G4301 | Picarro | Single or batch |
| [`import.GAIA`](#import.gaia) | GAIA2TECH ECOFlux | GAIA2TECH | Single or batch |
| [`import.GasmetPD`](#import.gasmetpd) | Gasmet PD (Custom) | Gasmet | Single or batch |
| [`import.GT5000`](#import.gt5000) | Gasmet GT5000 | Gasmet | Single or batch |
| [`import.HT8850`](#import.ht8850) | Healthy Photon HT8850 | Healthy Photon | Single or batch |
| [`import.LI6400`](#import.li6400) | LI-COR LI-6400 | LI-COR | Single or batch |
| [`import.LI7810`](#import.li7810) | LI-COR LI-7810 | LI-COR | Single or batch |
| [`import.LI7820`](#import.li7820) | LI-COR LI-7820 | LI-COR | Single or batch |
| [`import.LI8100`](#import.li8100) | LI-COR LI-8100 | LI-COR | Single or batch |
| [`import.LI8150`](#import.li8150) | LI-COR LI-8150 | LI-COR | Single or batch |
| [`import.LI8200`](#import.li8200) | LI-COR LI-8200 | LI-COR | Single or batch |
| [`import.LI8250`](#import.li8250) | LI-COR LI-8250 | LI-COR | Single or batch |
| [`import.N2Oi2`](#import.n2oi2) | Los Gatos N2Oi2 | Los Gatos | Single or batch |
| [`import.N2OM1`](#import.n2om1) | Los Gatos N2OM1 | Los Gatos | Single or batch |
| [`import.skyline`](#import.skyline) | Skyline2D | EarthBound Scientific | Single or batch |
| [`import.uCH4`](#import.uch4) | Los Gatos uCH4 | Los Gatos | Single or batch |
| [`import.UGGA`](#import.ugga) | Los Gatos UGGA | Los Gatos | Single or batch |
| [`import.uN2O`](#import.un2o) | Los Gatos uN2O | Los Gatos | Single or batch |

See individual function references for detailed documentation on each instrument.
