---
title: "`autoID`"
code-block-bg: true
---


 Uses an auxiliary file to identify start and end time of measurements, add
 a  list("UniqueID")  per measurement, and merge other auxiliary data required
 with the  list(list("goFlux"))  function.


## Description

Automatically define measurements' window based on an auxiliary file

## Usage

```r


autoID(

  inputfile,

  auxfile = NULL,

  obs.length = NULL,

  deadband = 0,

  crop.end = 0,

  shoulder = 60,

  drop = TRUE

)

```

## Arguments

| Parameter | Description |
|:----------|:--------------------------|
| `inputfile` | data.frame; output from import or align functions. |
| `auxfile` | data.frame; auxiliary data frame containing the columns start.time and UniqueID . start.time must contain a date and be in POSIXct format. The time zo... |
| `obs.length` | numerical; chamber closure time (seconds). Default is NULL. If obs.length is not provided, a column obs.length should be contained in auxfile or input... |
| `deadband` | numerical; time (seconds) at the start of the measurement, after chamber closure, to be removed from the time stamps used to estimate the flux. |
| `crop.end` | numerical; time (seconds) at the end of the measurement, before chamber opening, to be removed from the time stamps used to estimate the flux. |
| `shoulder` | numerical; time before and after measurement in observation window (seconds). Default is 60 seconds. If the time between two measurements is smaller t... |
| `drop` | logical; if drop = TRUE (default), time stamps without an assigned UniqueID are removed from the final data frame. |

## Value


 A merged data.frame between the  list("inputfile")  and the  list("auxfile") ,
          with the additional columns  list("flag") ,  list("Etime")  and  list("obs.length") .


## Details


 Note that, if the time between two measurements is smaller than  list("shoulder") ,
 the time stamps are duplicated, which can result in an output data frame
 larger (more rows) than the  list("inputfile") . Conversely, if  list("drop = TRUE") ,
 time stamps without an assigned  list("UniqueID")  are removed from the final data
 frame, which can result in an output data frame smaller (less rows) than the
 list("inputfile") .


## Examples

```r


# How to use in different situations:

library(dplyr)



## with a LGR instrument and an auxiliary file (.txt)

aux.path <- system.file("extdata", "aux_UGGA/aux_UGGA.txt", package = "goFlux")

auxfile <- read.delim(aux.path) %>%

  mutate(start.time = as.POSIXct(start.time, tz = "UTC"))

data(imp.UGGA)

autoID.UGGA <- autoID(inputfile = imp.UGGA, auxfile = auxfile, obs.length = 180)



## with a LI-COR instrument and the Smart Chamber as auxiliary file

data(imp.LI8200)

data(imp.LI7820)

autoID.LI7820 <- autoID(inputfile = imp.LI7820, deadband = 20, auxfile = imp.LI8200)



```

## See Also


 For a manual identification of start and end of gas measurements,
 see the functions  list(list("obs.win"))  and
 list(list("click.peak2")) .


