---
title: "`flux.plot`"
code-block-bg: true
---


 Returns a list of plots, drawn from flux results (output from the functions
 list(list("goFlux"))  and  list(list("best.flux")) ).
 The plots are customizable.


## Description

Plots for quality checking of GHG flux measurements

## Usage

```r


flux.plot(

  flux.results,

  dataframe,

  gastype,

  shoulder = 30,

  plot.legend = c("MAE", "AICc", "k.ratio", "g.factor"),

  plot.display = c("MDF", "prec"),

  quality.check = TRUE,

  flux.unit = NULL,

  flux.term.unit = NULL,

  best.model = TRUE,

  p.val.disp = "round",

  side = "left"

)

```

## Arguments

**`list("flux.results")`**

: list("a data.frame; output from the function\n", list(list("best.flux")))

**`list("dataframe")`**

: list("a data.frame containing gas measurements (see ", list("gastype"), "\n", "below) and the following columns: ", list("UniqueID"), ", ", list("Etime"), "\n", "and ", list("flag"), " (same ", list("dataframe"), " as used with the function\n", list(list("goFlux")), "). ", list("chamID"), " may be used\n", "instead of ", list("UniqueID"), ".")

**`list("gastype")`**

: list("character string; specifies which column was used for the\n", "flux calculations. Must be one of the following: \"CO2dry_ppm\",\n", "\"COdry_ppb\", \"CH4dry_ppb\", \"N2Odry_ppb\", \"NO2dry_ppb\", \"NOdry_ppb\",\n", "\"NH3dry_ppb\" or \"H2O_ppm\".")

**`list("shoulder")`**

: list("numerical value; time before and after measurement in observation\n", "window (seconds). Default is 30 seconds.")

**`list("plot.legend")`**

: list("character vector; specifies which parameters should be\n", "displayed in a legend above each plot. \"flux\" is always\n", "displayed. A maximum of 6 parameters can be displayed in the\n", "legend (including \"flux\"). Chose up to five extra parameters\n", "from the following: \"MAE\", \"RMSE\", \"AICc\", \"SErel\", \"SE\",\n", "\"r2\", \"LM.p.val\", \"HM.k\", \"k.max\", \"k.ratio\" and \"g.factor\".\n", "Default is ", list("plot.legend = c(\"MAE\", \"AICc\", \"k.ratio\", \"g.factor\")"), ".")

**`list("plot.display")`**

: list("character vector; specifies which parameters should be\n", "displayed on the plot. Choose from the following: \"C0\",\n", "\"Ci\", \"cham.close\", \"cham.open\", \"crop\", \"MDF\", \"nb.obs\",\n", "\"flux.term\" and \"prec\". Default is\n", list("plot.display = c(\"MDF\", \"prec\")"), ".")

**`list("quality.check")`**

: list("logical; if ", list("quality.check = TRUE"), ", the column\n", list("quality.check"), " (output from the function\n", list(list("best.flux")), ") is displayed\n", "below the plot.")

**`list("flux.unit")`**

: list("character string; flux units to be displayed on the plots.\n", "By default, the units are\n", list(list("html"), list(list("µmol m-2s-1")), list(list(list("µmol m^{-2}s^{-1}"), list("ASCII")))), "\n", "(if initial concentration is ppm, e.g. CO2dry_ppm) and\n", list(list("html"), list(list("nmol m-2s-1")), list(list(list("nmol m^{-2}s^{-1}"), list("ASCII")))), "\n", "(if initial concentration is ppb, e.g. CH4dry_ppb).\n", list(), " ", list(), "\n", 
    "For example, one may want to use\n", list(list("html"), list(list("nmol kg-1h-1")), list(list(list("µmol kg^{-1}h^{-1}"), list("ASCII")))), "\n", "for incubated soil samples. In such a case, write\n", list("flux.unit = \"nmol~kg^-1*h^-1\""), ".")

**`list("flux.term.unit")`**

: list("character string; units for the flux term to be displayed\n", "on the plots. By default, the units are\n", list(list("html"), list(list("mol m-2")), list(list(list("mol m^{-2}"), list("ASCII")))), ":\n", list("flux.term.unit = \"mol~m^-2\""))

**`list("best.model")`**

: list("logical; if ", list("best.model = TRUE"), ", display a star sign\n", "next to the best model selected by the function\n", list(list("best.flux")), ".")

**`list("p.val.disp")`**

: list("character string; indicates how the ", list("p-value"), " should\n", "be displayed in the legend above the plot. Choose one of\n", "the following: \"star\", \"round\", \"value\".")

**`list("side")`**

: list("character string; choose a side to display\n", list(list("html"), list(list("C0")), list(list(list("mol C[0]"), list("ASCII")))), " and\n", list(list("html"), list(list("Ci")), list(list(list("mol C[i]"), list("ASCII")))), " values.\n", "By default, they are displayed on the left side of the plot.")

## Value


 A list of plots, one per  list("UniqueID") , drawn from flux results (output
 from the functions  list(list("goFlux"))  and
 list(list("best.flux")) ).


## Details


 In  list("flux.results") , one may choose to use the output from the
 list(list("goFlux"))  function instead. However, in that case,
 any element produced by the function  list(list("best.flux")) 
 cannot be displayed on the plots.
 
 In  list("plot.legend") , one may choose to display up to five additional parameters
 in a legend above the plots. Some parameters are displayed for both the linear
 model ( list(list("LM.flux")) ) and the non-linear model
 ( list(list("HM.flux")) ): Mean Absolute Error ( list("MAE") ),
 Root Mean Square Error ( list("RMSE") ), Aikaike's Information Criterion
 corrected for small sample size ( list("LM.AICc") ), Standard Error ( list("SE") ),
 relative Standard Error ( list("SErel") ), and coefficient of determination
 ( list("r2") ). The  list("p-value")  ( list("LM.p.val") ) is displayed for the linear
 model only. The kappa ( list("HM.k") ), kappa-max
 ( list(list("k.max")) ), kappa ratio ( list("k.ratio") ) and
 g-factor ( list(list("g.factor")) ) are displayed for the
 Hutchinson and Mosier model only. One may choose to display no additional
 parameter with  list("plot.legend = NULL") .
 
 In  list("plot.display") , one may chose to display some parameters on the plot:
 The initial gas concentration ( list("C0") ) for both models, the assumed
 concentration of constant gas source below the surface ( list("Ci") ) calculated
 from the Hutchinson and Mosier model, the number of observations
 ( list("nb.obs") ) flagged, the Minimal Detectable Flux
 ( list(list("MDF")) ), the flux term
 ( list(list("flux.term")) ), the instrument precision
 ( list("prec") ), the chamber closure ( list("cham.close") ) and opening
 ( list("cham.open") ) (indicated with a green star), and the data points between
 chamber closure and opening that have been removed ( list("crop") ) (indicated
 in light red). For manual chamber measurements, because there is no automatic
 chamber closure and opening, no green stars can be displayed. In addition,
 list("crop")  is only relevant if data points have been removed with the
 function  list("crop.meas()")  (this function is not available yet).
 One may choose to display none of these parameters with  list("plot.display = NULL") .
 The order in which  list("prec") ,  list("flux.term") ,  list("MDF")  and  list("nb.obs") 
 are put in  list("plot.display = c()")  decides the order in which they are
 displayed at the bottom of the plot.
 
 In  list("flux.unit") , remember to multiply the flux results with an appropriate
 factor to convert the results from a unit to another. If kilograms of soil
 were used to calculate the fluxes (see the details section of the function
 list(list("goFlux")) ), the units would be
 list(list("html"), list(list("µmol kg-1s-1")), list(list(list("µmol kg^{-1}s^{-1}"), list("ASCII")))) .
 To convert the units to
 list(list("html"), list(list("µmol kg-1h-1")), list(list(list("µmol kg^{-1}h^{-1}"), list("ASCII")))) 
 instead, one would need to multiply the flux results by 3600 to convert from
 seconds to hours. To print non-ASCII characters use Unicode. For example, to
 print the Greek letter "mu" ( list(list("µ")) ), use the Unicode  list("\\u00B5") :
 list("flux.unit = \"\\u00B5mol~kg^-1*h^-1\"") .
 
 In  list("p.val.disp") , if  list("p.val.disp = \"star\"") , the  list("p-values")  will
 be displayed as star symbols (asterisks) as follows: ***, ** or * for
 list("p-values")  of p < 0.001, p < 0.01 and p < 0.05, respectively. If
 list("p.val.disp = \"round\"") , the  list("p-values")  are rounded to p < 0.001,
 p < 0.01 and p < 0.05. If  list("p.val.disp = \"value\"") , the actual values are
 displayed, rounded to two significant numbers.
 
 In  list("gastype") , the gas species listed are the ones for which this package
 has been adapted. Please write to the maintainer of this package for
 adaptation of additional gases.


## Examples

```r


data(manID.UGGA)

CO2_flux <- goFlux(manID.UGGA, "CO2dry_ppm")

criteria <- c("MAE", "AICc", "g.factor", "MDF")

CO2_best <- best.flux(CO2_flux, criteria)

CO2_plots <- flux.plot(

  flux.results = CO2_best, dataframe = manID.UGGA,

  gastype = "CO2dry_ppm", quality.check = TRUE,

  plot.legend = c("MAE", "AICc", "k.ratio", "g.factor"),

  plot.display = c("Ci", "C0", "MDF", "prec", "nb.obs", "flux.term"))



```

## See Also


 See also the functions  list(list("goFlux")) ,
           list(list("best.flux"))  and
           list(list("flux2pdf")) 
          for more information about usage.
 
 Look up the functions  list(list("g.factor")) ,
           list(list("k.max")) ,
           list(list("MDF")) ,
           list(list("flux.term")) ,
           list(list("LM.flux"))  and
           list(list("HM.flux"))  for more information about
          these parameters.


