---
title: "`iso.comp`"
code-block-bg: true
---


 Extracts the y-intercept of the regression between the isotope ratios plotted
 against the inverse of the gas concentration
 ( list(list("html"), list(list("CO<sub>2</sub>")), list(list(list("CO[2]"), list("ASCII"))))  or
 list(list("html"), list(list("N<sub>2</sub>O")), list(list(list("N[2]O"), list("ASCII")))) )


## Description

Determine the isotopic composition of
 list(list("html"), list(list("CO<sub>2</sub>")), list(list(list("CO[2]"), list("ASCII"))))  and
 list(list("html"), list(list("N<sub>2</sub>O")), list(list(list("N[2]O"), list("ASCII"))))  measurements

## Usage

```r


iso.comp(

  dataframe,

  CO2dry_ppm = "CO2dry_ppm",

  delta_13C = "Delta_Raw_iCO2",

  N2Odry_ppb = "N2Odry_ppb",

  delta_15N = "d15N",

  delta_18O = "d18O",

  save.plots

)

```

## Arguments

| Parameter | Description |
|:----------|:--------------------------|
| `dataframe` | a data.frame containing measurements of isotopic fractions of html CO2 CO[2] ASCII or html N2O N[2]O ASCII and a UniqueID (or chamID ) per measurement... |
| `CO2dry_ppm, delta_13C` | character string; specifies which columns should be used for html CO2 CO[2] ASCII measurements, and the delta 13C, respectively. |
| `N2Odry_ppb, delta_15N, delta_18O` | character string; specifies which columns should be used for html N2O N[2]O ASCII measurements, the delta 15N and the delta 18O, respectively. |
| `save.plots` | character string; a file path with the extension .pdf to save Keeling plots. By default plots are not saved. |

## Value


 A data frame of the isotopic composition per measurement (UniqueID)


## Examples

```r


data(manID.G2201i)

my.iso.comp <- iso.comp(manID.G2201i)

```

## See Also


 list(list("import.G2201i")) 


