---
title: "`import.LI8250`"
code-block-bg: true
---


 Imports single raw data files from the LI-COR Multiplexer (LI-8250)


## Description

Import function for LI-COR Multiplexer (LI-8250)

## Usage

```r


import.LI8250(

  inputfile,

  date.format = "ymd",

  timezone = "UTC",

  save = FALSE,

  keep_all = FALSE,

  inst1,

  inst2 = NULL,

  gas1,

  gas2 = NULL,

  prec1,

  prec2 = NULL,

  dry1 = T,

  dry2 = T,

  SWC.col,

  Tsoil.col

)

```

## Arguments

**`list("inputfile")`**

: list("character string; the name of a file with the extension .82z")

**`list("date.format")`**

: list("character string; specifies the date format found in the\n", "raw data file. Choose one of the following: \"dmy\", \"ymd\",\n", "or \"mdy\". Default is \"ymd\", as it is the date format from\n", "the example data file provided.")

**`list("timezone")`**

: list("character string; a time zone in which to import the data to\n", "POSIXct format. Default is \"UTC\". Note about time zone: it is\n", "recommended to use the time zone \"UTC\" to avoid any issue\n", "related to summer time and winter time changes.")

**`list("save")`**

: list("logical; if ", list("save = TRUE"), ", saves the file as an .RData file\n", "in a RData folder in the current working directory. If\n", list("save = FALSE"), ", returns the file in the Console, or load in\n", "the Environment if assigned to an object.")

**`list("keep_all")`**

: list("logical; if ", list("keep_all = TRUE"), ", keep all columns from the\n", "raw file. The default is ", list("keep_all = FALSE"), ", and columns\n", "that are not necessary for gas flux calculation are removed.")

**`list("inst1, inst2")`**

: list("character strings; a pattern to match the columns\n", "containing the name of each instrument. For example, with a LI-COR\n", "LI-7810, ", list("inst1 = \"LI-7810\""), " and ", list("inst2 = NULL"), ", which\n", "matches the example data file provided with the package.")

**`list("gas1, gas2")`**

: list("character vectors; a pattern to match the columns\n", "containing each gas measurement. For example, with a LI-COR LI-7810\n", list("gas1 = c(\"CO2_DRY\", \"CH4_DRY\", \"H2O\")"), " and ", list("gas2 = NULL"), ",\n", "which matches the example data file provided with the package.")

**`list("prec1, prec2")`**

: list("numerical vectors; the precision of the instrument\n", "for each gas mentioned in ", list("gas1"), " and ", list("gas2"), ". For example,\n", "with a LI-COR LI-7810, ", list("prec1 = c(3.5, 0.6, 45)"), " and\n", list("prec2 = NULL"), ", which matches the example data file provided with\n", "the package. Note that the order in the arguments ", list("precX"), " must\n", "match the order of the arguments in ", list("gasX"), ".")

**`list("dry1, dry2")`**

: list("logical; are the gas measurements compensated for water\n", "vapor (dry fraction)? If ", list("dryX = TRUE"), " (default), the gases are\n", "compensated for water vapor, and will be named accordingly. For\n", "example, the column \"CO2_DRY\" will become \"CO2dry_ppm\".")

**`list("Tsoil.col, SWC.col")`**

: list("character string; a pattern to match the columns\n", "that fit the corresponding parameter.")

## Value


 A data frame containing raw data from the LI-COR Multiplexer LI-8250.


## Details


 Files with the format .82z are zip archives that include all measurements
 that occurred at a given port for one observation. Each .82z file includes
 two files: a data.csv file and a metadata.json file. Raw files names for
 .82z files are formatted with the instrument serial number and a time stamp
 (serial-number-YYYYMMDDHHMMSS.82z). In  list("date.format") , the date format
 refers to the date format in the file name. Alternatively, the date format
 can be found in the data.csv file extracted from the .82z file, under the
 column "Date".
 
 Note that this function was designed for the following units in the raw file,
 according to the data dictionary of the LI-8250 Multiplexer
 list(list("https://www.licor.com/env/support/LI-8250/topics/files-page.html#Datadictionary"), list("online")) .
 list("\n", "  ", list(), " % v/v for soil water content (SWC)\n", "  ", list(), " litters for volumes\n", "  ", list(), " kPa for pressure\n", "  ", list(), " Celsius for temperature") 
 For each gas, the units are taken from the third row in the data.csv file.
 Currently, the function is adapted for use with LI-COR instruments (LI-870
 list(list("html"), list(list("CO2")), list(list(list("CO[2]"), list("ASCII")))) /
 list(list("html"), list(list("H2O")), list(list(list("H[2]O"), list("ASCII"))))  Analyzer or LI-78xx
 Trace Gas Analyzers). If you are using the function with a non-LI-COR
 instrument, please contact the maintainer of this package for support.
 
 Regarding the parameters  list("dryX") , in case of uncertainty, either contact
 your technical support or assume that gases are compensated for water vapor,
 which is normally the case.
 
 The precision of the instrument is needed to restrict kappa-max
 ( list(list("k.max")) ) in the non-linear flux calculation
 ( list(list("HM.flux")) ). Kappa-max is inversely proportional to
 instrument precision. If the precision of your instrument is unknown, it is
 better to use a low value (e.g. 1 ppm for
 list(list("html"), list(list("CO2")), list(list(list("CO[2]"), list("ASCII")))) , or 1 ppb for
 list(list("html"), list(list("CH4")), list(list(list("CH[4]"), list("ASCII")))) ) to allow for more
 curvature, especially for water vapor fluxes, or very long measurements, that
 are normally curved.
 
 According to the data dictionary of the LI-8250 Multiplexer
 list(list("https://www.licor.com/env/support/LI-8250/topics/files-page.html#Datadictionary"), list("online")) ,
 the column STATE indicates the chamber state, where, for example, 1 = closing
 and 5 = closed.


## Examples

```r


# Load file from downloaded package

file.path <- system.file("extdata", "LI8250/LI8250.82z", package = "goFlux")



# Run function

imp.LI8250 <- import.LI8250(inputfile = file.path, inst1 = "LI-7810",

                            gas1 = c("CO2_DRY", "CH4_DRY", "H2O"),

                            prec1 = c(3.5, 0.6, 45), SWC.col = "SWC_1",

                            Tsoil.col = "TS_1")

```

## See Also


 Use the wrapper function  list(list("import2RData")) 
          to import multiple files from the same folder path using any instrument.
 
 See also, import functions for other instruments:
           list(list("import.DX4015")) ,
           list(list("import.EGM5")) ,
           list(list("import.G2201i")) ,
           list(list("import.G2508")) ,
           list(list("import.G4301")) ,
           list(list("import.GAIA")) ,
           list(list("import.GasmetPD")) ,
           list(list("import.GT5000")) ,
           list(list("import.LI6400")) ,
           list(list("import.LI7810")) ,
           list(list("import.LI7820")) ,
           list(list("import.LI8100")) ,
           list(list("import.LI8200")) ,
           list(list("import.N2OM1")) ,
           list(list("import.uCH4")) ,
           list(list("import.uN2O")) ,
           list(list("import.UGGA")) 
 
 See  list(list("timezones"))  for a description of the underlying
          timezone attribute.


