---
title: "`import.skyline`"
code-block-bg: true
---


 Imports single raw gas measurement files from the SkyLine2D system from
 Earth Bound Scientific from the datalog file created by GAIA2TECH. Default
 settings are set for the Picarro G2508
 ( list(list("html"), list(list("CO<sub>2</sub>")), list(list(list("CO[2]"), list("ASCII")))) ,
 list(list("html"), list(list("CH<sub>4</sub>")), list(list(list("CH[4]"), list("ASCII")))) ,
 list(list("html"), list(list("N<sub>2</sub>O")), list(list(list("N[2]O"), list("ASCII"))))  and
 list(list("html"), list(list("H<sub>2</sub>O")), list(list(list("H[2]O"), list("ASCII")))) ), to match the
 example data file provided with the package.


## Description

Import function for the SkyLine2D system linked to one GHG analyzer

## Usage

```r


import.skyline(

  inputfile,

  date.format = "ymd",

  timezone = "UTC",

  save = FALSE,

  keep_all = FALSE,

  deadband = 0,

  shoulder = 20,

  CH.col = "CH ID",

  CH.clo.col = "Chamber closed",

  sensor1 = "Analog Sensor1",

  sensor2 = "Analog Sensor2",

  inst = "Instrument",

  gas = c("CO2", "CH4 Dry", "N2O Dry", "H2O"),

  prec = c(0.24, 0.3, 5, 500),

  dry = T

)

```

## Arguments

**`list("inputfile")`**

: list("character string; the name of a file with the extension .csv")

**`list("date.format")`**

: list("character string; specifies the date format found in the\n", "raw data file. Choose one of the following: \"dmy\", \"ymd\",\n", "or \"mdy\". Default is \"ymd\", as it is the date format from\n", "the example data file provided.")

**`list("timezone")`**

: list("character string; a time zone in which to import the data to\n", "POSIXct format. Default is \"UTC\". Note about time zone: it is\n", "recommended to use the time zone \"UTC\" to avoid any issue\n", "related to summer time and winter time changes.")

**`list("save")`**

: list("logical; if ", list("save = TRUE"), ", saves the file as an .RData file\n", "in a RData folder in the current working directory. If\n", list("save = FALSE"), ", returns the file in the Console, or load in\n", "the Environment if assigned to an object.")

**`list("keep_all")`**

: list("logical; if ", list("keep_all = TRUE"), ", keep all columns from the raw\n", "file. The default is ", list("keep_all = FALSE"), ", and columns that\n", "are not necessary for gas flux calculation are removed.")

**`list("deadband")`**

: list("numerical; define a deadband at the start of measurements (seconds).")

**`list("shoulder")`**

: list("numerical; include background data points before and after\n", "the measurement (seconds).")

**`list("CH.clo.col, CH.col")`**

: list("character string; a pattern to match columns that\n", "fit the corresponding parameters: ", list("CH.col = \"CH ID\""), " and\n", list("CH.clo.col = \"Chamber closed\""), ".")

**`list("sensor1, sensor2")`**

: list("character strings; a pattern to match the columns\n", "containing the name of each sensor. By default,\n", list("sensor1 = \"Analog Sensor1\""), ", ", list("sensor2 = \"Analog Sensor2\""), ",\n", "to match the example data file provided with the package. Set to NULL\n", "to ignore these columns.")

**`list("inst")`**

: list("character string; a pattern to match the column containing the\n", "name of the GHG analyzer: ", list("inst = \"Instrument\""), ".")

**`list("gas")`**

: list("character vector; a pattern to match the columns containing each\n", "gas measurement. By default, ", list("gas = c(\"CO2\", \"CH4 Dry\", \"N2O Dry\", \"H2O\")"), ",\n", "to match the example data file provided with the package.")

**`list("prec")`**

: list("numerical vector; the precision of the instrument for each gas\n", "mentioned in ", list("gas"), ". By default, ", list("prec = c(0.24, 0.3, 5, 500)"), ",\n", "to match the example data file provided with the package. Note that\n", "the order in the arguments ", list("prec"), " must match the order of the\n", "arguments in ", list("gas"), ".")

**`list("dry")`**

: list("logical; are the gas measurements compensated for water vapor\n", "(dry fraction)? If ", list("dry = TRUE"), " (default), the gases are already\n", "compensated for water vapor. Otherwise, the gases will be converted to\n", "a dry fraction.")

## Value


 A data frame containing raw data from the SkyLine2D system


## Details


 This function has been designed for the SkyLine2D system file generated by
 GAIA2TECH synced with the Picarro G2508
 ( list(list("html"), list(list("CO2")), list(list(list("CO[2]"), list("ASCII")))) ,
 list(list("html"), list(list("CH4")), list(list(list("CH[4]"), list("ASCII")))) ,
 list(list("html"), list(list("N2O")), list(list(list("N[2]O"), list("ASCII"))))  and
 list(list("html"), list(list("H2O")), list(list(list("H[2]O"), list("ASCII")))) )). If this function
 could be useful for you, but does not meet your needs, please contact the
 maintainer of this package for potential adaptations.
 
 In  list("date.format") , the date format refers to a date found in the raw data
 file, not the date format in the file name. For the SkyLine2D system,
 the date is found in the column "Titles:". Be mindful that when you open a
 .csv file in Excel, the software often changes date formats. To avoid any
 discrepancy, open the file in a text file.
 
 The argument  list("CH.clo.col")  corresponds to the column "Chamber closed".
 Any number above 0 in that column indicate that the chamber is closed. The
 argument  list("CH.col")  corresponds to the column "CH ID" indicating which
 chamber is active.
 
 For each gas, the units are taken from the second row in the raw file (Units:).
 If your instrument uses different units, either convert the units after
 import, change the settings on your instruments, or contact the maintainer of
 this package for support.
 
 Regarding the parameters  list("dry") , in case of uncertainty, either contact
 your technical support or assume that gases are compensated for water vapor,
 which is normally the case.
 
 As opposed to the other import functions, there is no option to "keep_all" with
 this instrument. If you would like to import additional data using this
 function, please contact the maintainer of this package for support.
 
 The precision of the instrument is needed to restrict kappa-max
 ( list(list("k.max")) ) in the non-linear flux calculation
 ( list(list("HM.flux")) ). Kappa-max is inversely proportional to
 instrument precision. If the precision of your instrument is unknown, it is
 better to use a low value (e.g. 1 ppm for
 list(list("html"), list(list("CO2")), list(list(list("CO[2]"), list("ASCII"))))  and
 list(list("html"), list(list("H2O")), list(list(list("H[2]O"), list("ASCII")))) , or 1 ppb for
 list(list("html"), list(list("CH4")), list(list(list("CH[4]"), list("ASCII"))))  and
 list(list("html"), list(list("N2O")), list(list(list("N[2]O"), list("ASCII")))) ) to allow for more
 curvature, especially for water vapor fluxes, or very long measurements, that
 are normally curved. The default values given for instrument precision are
 the ones found online for the latest models of the
 list(list("https://www.picarro.com/environmental/products/g2508_gas_concentration_analyzer"), list("Picarro G2508")) ,
 available at the time of the creation of this function (10-2025).


## Examples

```r


# Load file from downloaded package

file.path <- system.file("extdata", "skyline/skyline.csv", package = "goFlux")



# Run function

imp.skyline <- import.skyline(inputfile = file.path)

```

## See Also


 Use the wrapper function  list(list("import2RData")) 
          to import multiple files from the same folder path using any instrument.
 
 See also, import functions for other instruments:
           list(list("import.DX4015")) ,
           list(list("import.EGM5")) ,
           list(list("import.G2201i")) ,
           list(list("import.G2508")) ,
           list(list("import.G4301")) ,
           list(list("import.GAIA")) ,
           list(list("import.GasmetPD")) ,
           list(list("import.GT5000")) ,
           list(list("import.LI6400")) ,
           list(list("import.LI7810")) ,
           list(list("import.LI7820")) ,
           list(list("import.LI8100")) ,
           list(list("import.LI8200")) ,
           list(list("import.LI8250")) ,
           list(list("import.N2OM1")) ,
           list(list("import.N2Oi2")) ,
           list(list("import.uCH4")) ,
           list(list("import.uN2O")) ,
           list(list("import.UGGA")) 
 
 See  list(list("timezones"))  for a description of the underlying
          timezone attribute.


