---
title: "`import.G2201i`"
code-block-bg: true
---


 Imports single raw gas measurement files from the Picarro G2201-i with the
 extension .dat ( list(list("html"), list(list("CO<sub>2</sub>")), list(list(list("CO[2]"), list("ASCII"))))  and
 list(list("html"), list(list("CH<sub>4</sub>")), list(list(list("CH[4]"), list("ASCII"))))  isotopic analyzer)


## Description

Import function for the Picarro G2201-i Isotopic Analyzer

## Usage

```r


import.G2201i(

  inputfile,

  date.format = "ymd",

  timezone = "UTC",

  save = FALSE,

  keep_all = FALSE,

  prec = c(0.2, 50, 100),

  CH4 = "HP_12CH4_dry",

  CO2 = "12CO2_dry",

  sum = TRUE,

  range = 10

)

```

## Arguments

**`list("inputfile")`**

: list("character string; the name of a file with the extension .dat")

**`list("date.format")`**

: list("character string; specifies the date format found in the\n", "raw data file. Choose one of the following: \"dmy\", \"ymd\",\n", "or \"mdy\". Default is \"ymd\", as it is the date format from\n", "the example data file provided.")

**`list("timezone")`**

: list("character string; a time zone in which to import the data to\n", "POSIXct format. Default is \"UTC\". Note about time zone: it is\n", "recommended to use the time zone \"UTC\" to avoid any issue\n", "related to summer time and winter time changes.")

**`list("save")`**

: list("logical; if ", list("save = TRUE"), ", saves the file as an .RData file\n", "in a RData folder in the current working directory. If\n", list("save = FALSE"), ", returns the file in the Console, or load in\n", "the Environment if assigned to an object.")

**`list("keep_all")`**

: list("logical; if ", list("keep_all = TRUE"), ", keep all columns from the raw\n", "file. The default is ", list("keep_all = FALSE"), ", and columns that\n", "are not necessary for gas flux calculation are removed.")

**`list("prec")`**

: list("numerical vector; the precision of the instrument for each gas,\n", "in the following order: \"CO2dry_ppm\", \"CH4dry_ppb\" and \"H2O_ppm\".\n", "The default is ", list("prec = c(0.2, 50, 100)"), ".")

**`list("CH4")`**

: list("character string; which column should be used for\n", list(list("html"), list(list("CH4")), list(list(list("CH[4]"), list("ASCII")))), " concentration.\n", "By default, ", list("CH4 = \"HP_12CH4_dry\""), ".")

**`list("CO2")`**

: list("character string; which column should be used for\n", list(list("html"), list(list("CO2")), list(list(list("CO[2]"), list("ASCII")))), " concentration.\n", "By default, ", list("CO2 = \"12CO2_dry\""), ".")

**`list("sum")`**

: list("logical; if ", list("sum = TRUE"), " (default), the arguments ", list("CH4"), " and\n", list("CO2"), " are ignored and, instead, both fractions (carbon isotope\n", "12 and 13) of each gas, are summed after correction for water vapor,\n", "to obtain the total gas concentration. See the argument ", list("range"), "\n", "for the selection between the HP or the HR measurement of\n", list(list("html"), list(list("CH4")), list(list(list("CH[4]"), list("ASCII")))), " concentration.")

**`list("range")`**

: list("numerical value; at which threshold should the function select\n", "between high precision (HP) and high resolution (HR) of\n", list(list("html"), list(list("CH4")), list(list(list("CH[4]"), list("ASCII")))), "\n", "concentration? The default is ", list("range = 10"), ". If the methane\n", "concentration recorded in the column ", list("HP_12CH4_dry"), " is above\n", "10 ppm, the concentration from the columns ", list("HR_12CH4_dry"), "\n", "and ", list("HR_13CH4"), " are used for the sum instead of HP.")

## Value


 A data frame containing raw data from Picarro G2201-i isotopic analyzer.


## Details


 In  list("date.format") , the date format refers to a date found in the raw data
 file, not the date format in the file name. For the instrument G2201-i, the date
 is found in the column "DATE".
 
 The arguments  list("CH4")  and  list("CO2")  require the user to specify which
 columns contain the two gases of interest among the following for  list("CH4") :
 list("\n", "  ", list(), " HP_12CH4\n", "  ", list(), " HP_12CH4_dry\n", "  ", list(), " HP_13CH4\n", "  ", list(), " HR_12CH4\n", "  ", list(), " HR_12CH4_dry\n", "  ", list(), " HR_13CH4") 
 And among the following for  list("CO2") :
 list("\n", "  ", list(), " 12CO2\n", "  ", list(), " 12CO2_dry\n", "  ", list(), " 13CO2\n", "  ", list(), " 13CO2_dry") 
 Note that, HP stands for  list(list("html"), list(list("CH4")), list(list(list("CH[4]"), list("ASCII")))) 
 concentration measured with strong line for high precision but limited range
 and HR stands for  list(list("html"), list(list("CH4")), list(list(list("CH[4]"), list("ASCII")))) 
 concentration measured with high range (between 10 and 1000 ppm). In addition,
 _dry stands for dry mole fraction of gases, corrected for water vapor. Finally,
 12 and 13 indicate each carbon isotope contained in each gas. If one selects
 one of the non-dry mole fraction, it will be corrected for water vapor during
 the import process.
 
 Note that this function was designed for the following units in the raw file:
 list("\n", "  ", list(), " ppm for ", list(list("html"), list(list("CO2")), list(list(list("CO[2]"), list("ASCII")))), " and\n", "        ", list(list("html"), list(list("CH4")), list(list(list("CH[4]"), list("ASCII")))), "\n", "  ", list(), " percent (%) for ", list(list("html"), list(list("H2O")), list(list(list("H[2]O"), list("ASCII")))), "\n", "  ", list(), " Torr for pressure\n", "  ", list(), " Celsius for temperature") 
 If your Picarro G2201-i uses different units, either convert the units after
 import, change the settings on your instrument, or contact the maintainer of
 this package for support.
 
 The precision of the instrument is needed to restrict kappa-max
 ( list(list("k.max")) ) in the non-linear flux calculation
 ( list(list("HM.flux")) ). Kappa-max is inversely proportional to
 instrument precision. If the precision of your instrument is unknown, it is
 better to use a low value (e.g. 1 ppm) to allow for more curvature,
 especially for water vapor fluxes, or very long measurements, that are
 normally curved. The default values given for instrument precision are the
 ones found  list(list("https://www.picarro.com/environmental/products/g2201i_isotopic_analyzer"), list("online")) 
 for the latest model of this instrument, available at the time of the
 creation of this function (05-2025).


## Examples

```r


# Load file from downloaded package

file.path <- system.file("extdata", "G2201i/2025/05/13/G2201i.dat", package = "goFlux")



# Run function

imp.G2201i <- import.G2201i(inputfile = file.path)

```

## See Also


 Use the wrapper function  list(list("import2RData")) 
          to import multiple files from the same folder path using any instrument.
 
 See also, import functions for other instruments:
           list(list("import.DX4015")) ,
           list(list("import.EGM5")) ,
           list(list("import.G2508")) ,
           list(list("import.G4301")) ,
           list(list("import.GAIA")) ,
           list(list("import.GasmetPD")) ,
           list(list("import.GT5000")) ,
           list(list("import.LI6400")) ,
           list(list("import.LI7810")) ,
           list(list("import.LI7820")) ,
           list(list("import.LI8100")) ,
           list(list("import.LI8200")) ,
           list(list("import.LI8250")) ,
           list(list("import.N2OM1")) ,
           list(list("import.N2Oi2")) ,
           list(list("import.uCH4")) ,
           list(list("import.uN2O")) ,
           list(list("import.UGGA")) 
 
 See  list(list("timezones"))  for a description of the underlying
          timezone attribute.


