---
title: "`obs.win`"
code-block-bg: true
---


 Split gas data into one observation window per gas measurement
 and create a list of data frames (one data frame per UniqueID).


## Description

Define measurements' window for manual identification

## Usage

```r


obs.win(

  inputfile,

  auxfile = NULL,

  gastype = deprecated(),

  obs.length = NULL,

  shoulder = 120

)

```

## Arguments

**`list("inputfile")`**

: list("data.frame; output from import or align functions.")

**`list("auxfile")`**

: list("data.frame; auxiliary data frame containing the columns\n", list("start.time"), " and ", list("UniqueID"), ". ", list("start.time"), " must\n", "contain a date and be in POSIXct format. The time zone must be\n", "the same as the POSIX.time in ", list("inputfile"), ". The default\n", "time zone for the import functions is \"UTC\". A data frame from\n", "the Smart Chamber (LI-8200) can be used as an auxiliary file.\n", "In that case, ", list("chamID"), " will be used instead of ", list("UniqueID"), 
    ",\n", "if ", list("UniqueID"), " cannot be found.")

**`list("gastype")`**

: list("deprecated")

**`list("obs.length")`**

: list("numerical; chamber closure time (seconds). Default is NULL.\n", "If ", list("obs.length"), " is not provided, a column ", list("obs.length"), "\n", "should be contained in ", list("auxfile"), " or ", list("inputfile"), ".\n", "Alternatively, ", list("obs.length"), " will be calculated from\n", list("start.time"), " and ", list("cham.open"), " or ", list("end.time"), "\n", "if found in ", list("auxfile"), " or ", list("inputfile"), ".")

**`list("shoulder")`**

: list("numerical; time before and after measurement in observation\n", "window (seconds). Default is 120 seconds.")

## Value


 a list of data frames, split by UniqueID, merging  list("inputfile") ,
          and  list("auxfile") . Additionally, adds some time (shoulder) before
          and after the chamber closure time to help identify the best window
          of measurement with the function  list(list("click.peak2")) .


## Examples

```r


# How to use in multiple situations:

library(dplyr)



## with a LGR instrument and an auxiliary file (.txt)

aux.path <- system.file("extdata", "aux_UGGA/aux_UGGA.txt", package = "goFlux")

auxfile <- read.delim(aux.path) %>%

  mutate(start.time = as.POSIXct(start.time, tz = "UTC"))

data(imp.UGGA)

ow.UGGA <- obs.win(inputfile = imp.UGGA, auxfile = auxfile,

                   obs.length = 180, shoulder = 60)



## with a LI-COR instrument and the Smart Chamber as auxiliary file

data(imp.LI8200)

data(imp.LI7820)

ow.LI7820 <- obs.win(inputfile = imp.LI7820, auxfile = imp.LI8200, shoulder = 60)



## with the LI-6400 and no auxiliary file

data(imp.LI6400)

ow.LI6400 <- obs.win(inputfile = imp.LI6400, shoulder = 0)



```

## See Also


 After defining the observation window with the function  list("obs.win") ,
          Use the function  list(list("click.peak2")) .
 
 For an automatic identification of gas measurements, see the function
 list(list("autoID")) .


