---
title: "`import.GasmetPD`"
code-block-bg: true
---


 Imports single raw gas measurement files from the GasmetPD, a custom made
 multiplexer
 ( list(list("html"), list(list("CO<sub>2</sub>")), list(list(list("CO[2]"), list("ASCII")))) ,
 list(list("html"), list(list("CH<sub>4</sub>")), list(list(list("CH[4]"), list("ASCII")))) ,
 list(list("html"), list(list("N<sub>2</sub>O")), list(list(list("N[2]O"), list("ASCII")))) ,
 list(list("html"), list(list("NO<sub>2</sub>")), list(list(list("NO[2]"), list("ASCII")))) , NO,
 list(list("html"), list(list("NH<sub>3</sub>")), list(list(list("NH[3]"), list("ASCII"))))  and
 list(list("html"), list(list("H<sub>2</sub>O")), list(list(list("H[2]O"), list("ASCII")))) )


## Description

Import function for the GasmetPD multiplexer from the University of Padova

## Usage

```r


import.GasmetPD(

  inputfile,

  date.format = "ymd",

  timezone = "UTC",

  save = FALSE,

  keep_all = FALSE,

  gas = c("CO2_ppm", "CH4_ppm", "N2O_ppm", "NH3_ppm", "H2O_pct"),

  prec = c(1.6, 13, 2, 23, 33)

)

```

## Arguments

**`list("inputfile")`**

: list("character string; the name of a file with the extension .txt")

**`list("date.format")`**

: list("character string; specifies the date format found in the\n", "raw data file. Choose one of the following: \"dmy\", \"ymd\",\n", "or \"mdy\". Default is \"ymd\", as it is the date format from\n", "the example data file provided.")

**`list("timezone")`**

: list("character string; a time zone in which to import the data to\n", "POSIXct format. Default is \"UTC\". Note about time zone: it is\n", "recommended to use the time zone \"UTC\" to avoid any issue\n", "related to summer time and winter time changes.")

**`list("save")`**

: list("logical; if ", list("save = TRUE"), ", saves the file as an .RData file\n", "in a RData folder in the current working directory. If\n", list("save = FALSE"), ", returns the file in the Console, or load in\n", "the Environment if assigned to an object.")

**`list("keep_all")`**

: list("logical; if ", list("keep_all = TRUE"), ", keep all columns from the raw\n", "file. The default is ", list("keep_all = FALSE"), ", and columns that\n", "are not necessary for gas flux calculation are removed.")

**`list("gas")`**

: list("character vector; a pattern to match the columns containing each\n", "gas measurement. Choose from: \"CO2_ppm\", \"CH4_ppm\", \"N2O_ppm\",\n", "\"NH3_ppm\", \"NO2_ppm\", \"NO_ppm\" and \"H2O_ppm\".")

**`list("prec")`**

: list("numerical vector; the precision of the instrument for each gas.\n", "Note that the order in the arguments ", list("prec"), " must match the\n", "order of the arguments in ", list("gas"), ".")

## Value


 A data frame containing raw data from the custom made multiplexer
          GasmetPD, from the University of Padova, Italy.


## Details


 In  list("date.format") , the date format refers to a date found in the raw data
 file, not the date format in the file name. For this instrument, the date
 is found in the column "Date".
 
 Note that this function was designed for the following units in the raw file:
 list("\n", "  ", list(), " ppm for ", list(list("html"), list(list("CO2")), list(list(list("CO[2]"), list("ASCII")))), ",\n", "  ", list(list("html"), list(list("CH4")), list(list(list("CH[4]"), list("ASCII")))), ",\n", "  ", list(list("html"), list(list("N2O")), list(list(list("N[2]O"), list("ASCII")))), ",\n", "  ", list(list("html"), list(list("NO2")), list(list(list("NO[2]"), list("ASCII")))), ", NO and\n", "  ", list(list("html"), list(list("NH3")), 
    list(list(list("NH[3]"), list("ASCII")))), "\n", "  ", list(), " percent (%) for ", list(list("html"), list(list("H2O")), list(list(list("H[2]O"), list("ASCII")))), "\n", "  ", list(), " mbar for pressure") 
 The function converts ambient pressure to kPa (Pcham), water vapor to ppm,
 and  list(list("html"), list(list("CH4")), list(list(list("CH[4]"), list("ASCII")))) ,
 list(list("html"), list(list("N2O")), list(list(list("N[2]O"), list("ASCII")))) ,
 list(list("html"), list(list("NO2")), list(list(list("NO[2]"), list("ASCII")))) , NO and
 list(list("html"), list(list("NH3")), list(list(list("NH[3]"), list("ASCII"))))  to ppb. If your
 instrument uses different units, either convert the units after import,
 change the settings on your instrument, or contact the maintainer
 of this package for support.
 
 The precision of the instrument is needed to restrict kappa-max
 ( list(list("k.max")) ) in the non-linear flux calculation
 ( list(list("HM.flux")) ). Kappa-max is inversely proportional to
 instrument precision. If the precision of your instrument is unknown, it is
 better to use a low value (e.g. 1 ppm for
 list(list("html"), list(list("CO2")), list(list(list("CO[2]"), list("ASCII"))))  and
 list(list("html"), list(list("H2O")), list(list(list("H[2]O"), list("ASCII")))) , or 1 ppb for
 list(list("html"), list(list("CH4")), list(list(list("CH[4]"), list("ASCII")))) ,
 list(list("html"), list(list("N2O")), list(list(list("N[2]O"), list("ASCII")))) ,
 list(list("html"), list(list("NO2")), list(list(list("NO[2]"), list("ASCII")))) , NO and
 list(list("html"), list(list("NH3")), list(list(list("NH[3]"), list("ASCII")))) ) to allow for more
 curvature, especially for water vapor fluxes, or very long measurements, that
 are normally curved. The default values given for instrument precision are
 the ones provided by the manufacturer upon request, for the latest model of
 this instrument available at the time of the creation of this function (07-2024).


## Examples

```r


# Load file from downloaded package

file.path <- system.file("extdata", "GasmetPD/GasmetPD.txt", package = "goFlux")



# Run function

imp.GasmetPD <- import.GasmetPD(inputfile = file.path)

```

## See Also


 Use the wrapper function  list(list("import2RData")) 
          to import multiple files from the same folder path using any instrument.
 
 See also, import functions for other instruments:
           list(list("import.DX4015")) ,
           list(list("import.EGM5")) ,
           list(list("import.G2201i")) ,
           list(list("import.G2508")) ,
           list(list("import.G4301")) ,
           list(list("import.GAIA")) ,
           list(list("import.GT5000")) ,
           list(list("import.LI6400")) ,
           list(list("import.LI7810")) ,
           list(list("import.LI7820")) ,
           list(list("import.LI8100")) ,
           list(list("import.LI8200")) ,
           list(list("import.LI8250")) ,
           list(list("import.N2OM1")) ,
           list(list("import.N2Oi2")) ,
           list(list("import.uCH4")) ,
           list(list("import.uN2O")) ,
           list(list("import.UGGA")) 
 
 See  list(list("timezones"))  for a description of the underlying
          timezone attribute.


