---
title: "`click.peak2`"
code-block-bg: true
---


 Identify the start and the end of a measurement by clicking on them in a
 scatter plot. First apply the function  list(list("obs.win"))  to
 identify the observation window of each measurement and then use the function
 list(list("click.peak2"))  (see examples below).


## Description

Manual identification of start and end of gas measurements

## Usage

```r


click.peak2(

  ow.list,

  gastype = "CO2dry_ppm",

  sleep = 3,

  plot.lim = c(380, 1000),

  seq = NULL,

  warn.length = 60,

  save.plots = NULL,

  width = 14,

  height = 8,

  abline = TRUE,

  abline_corr = TRUE

)

```

## Arguments

**`list("ow.list")`**

: list("list of data.frame; output from the function\n", list(list("obs.win")), ". Must contain the columns\n", list("gastype"), " (see below), ", list("POSIX.time"), " and ", list("UniqueID"), ".")

**`list("gastype")`**

: list("character string; specifies which gas should be displayed on\n", "the plot to manually select start time and end time of\n", "measurements. Must be one of the following: \"CO2dry_ppm\",\n", "\"COdry_ppb\", \"CH4dry_ppb\", \"N2Odry_ppb\", \"NO2dry_ppb\", \"NOdry_ppb\",\n", "\"NH3dry_ppb\" or \"H2O_ppm\". Default is \"CO2dry_ppm\".")

**`list("sleep")`**

: list("numerical value; delay before closing the resulting plot. Grants\n", "a delay between measurements to visually inspect the output\n", "before processing the next measurement. Sleep must be shorter\n", "than 10 seconds. If ", list("sleep = NULL"), ", the  plots will not close.")

**`list("plot.lim")`**

: list("numerical vector of length 2; sets the Y axis limits in the\n", "plots. Default values are set for a typical gas measurement\n", "of \"CO2dry_ppm\" from soils: ", list("plot.lim = c(380,1000)"), ".")

**`list("seq")`**

: list("a numerical sequence that indicates objects in a list. By default,\n", list("seq = NULL"), " and the function loops through all data frames\n", "in ", list("ow.list"), ".")

**`list("warn.length")`**

: list("numerical value; limit under which a measurement is flagged\n", "for being too short (", list("nb.obs < warn.length"), "). Default\n", "value is ", list("warn.length = 60"), ".")

**`list("save.plots")`**

: list("character string; a file path with the extension .pdf to\n", "save the plots produced with click.peak2. By default,\n", list("save.plot = NULL"), " and plots are not saved.")

**`list("width")`**

: list("numerical value; width of the pop-up window.")

**`list("height")`**

: list("numerical value; height of the pop-up window.")

**`list("abline")`**

: list("logical; if TRUE (default), blue vertical lines indicate\n", list("start.time"), " and ", list("end.time"), " on both plots.")

**`list("abline_corr")`**

: list("logical; if TRUE (default), red vertical lines indicate\n", list("start.time_corr"), " and ", list("end.time_corr"), " on validation plot.")

## Value


 A data.frame, identical to an unlisted version of the input
           list("ow.list") , with the additional columns  list("flag") ,  list("Etime") ,
           list("start.time_corr") ,  list("end.time_corr")  and  list("obs.length_corr") .


## Details


 The argument  list("plot.lim")  is used to remove any data points below and
 above the plot limits for a better view of the scatter plot. If the gas
 measurements are larger than the minimum or smaller than the maximum plot
 limit values, then the plot will automatically zoom in and adjust to those
 values. The default plot limits are set for a typical gas measurement of
 "CO2dry_ppm" from a soil respiration measurement:  list("plot.lim = c(380,1000)") ,
 where 380 ppm is the minimum plotted concentration, which should be close to
 atmospheric concentration, and 1000 ppm is the maximum plotted concentration,
 which correspond to a maximal accumulated concentration in the chamber before
 considering it an outlier (e.g. caused by breath or gas bubble). For other
 gasses, the user must specify the plot limits themselves. Here are some
 suggestions of plot limits for the other gases:
 list("\n", "  ", list(), " \"CH4dry_ppb\": ", list("plot.lim = c(2200, 1800)"), "\n", "  ", list(), " \"N2Odry_ppb\": ", list("plot.lim = c(250, 500)"), "\n", "  ", list(), " \"NH3dry_ppb\": ", list("plot.lim = c(0, 200)"), "\n", "  ", list(), " \"COdry_ppb\": ", list("plot.lim = c(0, 200)"), "\n", "  ", list(), " \"H2O_ppm\": ", list("plot.lim = c(10000, 20000)"), "\n") 
 These values will vary depending on ecosystem type and chamber application scheme.
 
 IMPORTANT! This function makes use of the function  list(list("identify")) 
 which is only supported on screen devices such as X11, windows and quartz.
 It is therefore essential to verify that your system options are compatible
 with this function before running it, to avoid errors. Use the function
 list("getOption(\"device\")")  to find which device your system uses.
 
 The argument  list("seq")  is used to select a subset of data frame from the list
 of data frames in  list("ow.list") . For example, to apply the function on the
 first measurement in the list, set  list("seq = 1") , or  list("seq = seq(1,10)") 
 for the first 10 measurements.
 
 list("warn.length")  is the limit below which the chamber closure time is
 flagged for being too short ( list("nb.obs < warn.length") ). Portable
 greenhouse gas analyzers typically measure at a frequency of 1 Hz. Therefore,
 for the default setting of  list("warn.length = 60") , the chamber closure time
 should be approximately one minute (60 seconds). If the number of
 observations is smaller than the threshold, a warning is printed: "Number of
 observations for UniqueID: 'UniqueID' is X observations".
 
 In  list("gastype") , the gas species listed are the ones for which this package
 has been adapted. Please write to the maintainer of this package for
 adaptation of additional gases.
 
 The arguments  list("width")  and  list("heigth")  are used with the function
 list(list("dev.new"))  to define the dimensions of the pop-up
 window.


## Examples

```r


# IMPORTANT! This function makes use of the function graphics::identify()

# which is only supported on screen devices such as X11, windows and quartz.

# It is therefore essential to verify that your system options are compatible

# with this function before running it, to avoid errors. Here is an example

# of how to modify your system options for graphics device:

list("\n", "default.device <- getOption(\"device\") # save default option\n", "options(device = \"X11\") # change system option to device = \"X11\"\n", "options(device = default.device) # revert back to default option ")




# There are multiple ways to use this function. Here are some examples:



library(dplyr)

list("\n", "## with a LGR instrument and an auxiliary file (.txt),\n", "## and plots saved as pdf\n", "aux.path <- system.file(\"extdata\", \"aux_UGGA/aux_UGGA.txt\", package = \"goFlux\")\n", "auxfile <- read.delim(aux.path) %>%\n", "  mutate(start.time = as.POSIXct(start.time, tz = \"UTC\"))\n", "data(imp.UGGA)\n", "ow.UGGA <- obs.win(inputfile = imp.UGGA, auxfile = auxfile,\n", "                   obs.length = 180, shoulder = 60)\n", "save.to <- paste(tempdir(), \"manID.UGGA.pdf\", sep = \"/\")\n", 
    "manID.UGGA <- click.peak2(ow.UGGA, save.plots = save.to)\n", "# In this example, plots are saved in a temporary directory using\n", "# the function tempdir(). To save files in your working directory\n", "# instead, use the function getwd().\n", "\n", "\n", "## with a LI-COR instrument, the Smart Chamber as auxiliary file\n", "## and only the first data frame selected\n", "data(imp.LI8200)\n", "data(imp.LI7820)\n", "ow.LI7820 <- obs.win(inputfile = imp.LI7820, auxfile = imp.LI8200, shoulder = 60)\n", 
    "manID.LI7820 <- click.peak2(ow.LI7820, gastype = \"N2Odry_ppb\",\n", "                            plot.lim = c(250,500), seq = 1)\n", "\n", "\n", "## with the LI-6400, no auxiliary file\n", "## and seq through the first 3 data frames\n", "data(imp.LI6400)\n", "ow.LI6400 <- obs.win(inputfile = imp.LI6400, shoulder = 0)\n", "manID.LI6400 <- click.peak2(ow.LI6400, seq = seq(1,3)) ")


```

## See Also


 See also  list(list("obs.win"))  to prepare a list of data.frame.
 
 For an automatic identification of gas measurements, see the function
 list(list("autoID")) .


