---
title: "`import.GT5000`"
code-block-bg: true
---


 Imports single raw gas measurement files from the Gasmet GT5000 gas analyzer
 (CO,  list(list("html"), list(list("CO<sub>2</sub>")), list(list(list("CO[2]"), list("ASCII")))) ,
 list(list("html"), list(list("CH<sub>4</sub>")), list(list(list("CH[4]"), list("ASCII")))) ,
 list(list("html"), list(list("N<sub>2</sub>O")), list(list(list("N[2]O"), list("ASCII")))) ,
 list(list("html"), list(list("NH<sub>3</sub>")), list(list(list("NH[3]"), list("ASCII"))))  and
 list(list("html"), list(list("H<sub>2</sub>O")), list(list(list("H[2]O"), list("ASCII")))) )
 with the extension .TXT


## Description

Import function for the Gasmet GT5000 Terra - Splashproof multigas FTIR
 analyzer

## Usage

```r


import.GT5000(

  inputfile,

  date.format = "ymd",

  timezone = "UTC",

  save = FALSE,

  keep_all = FALSE,

  prec = c(1.6, 23, 13, 2, 23, 33)

)

```

## Arguments

**`list("inputfile")`**

: list("character string; the name of a file with the extension .TXT")

**`list("date.format")`**

: list("character string; specifies the date format found in the\n", "raw data file. Choose one of the following: \"dmy\", \"ymd\",\n", "or \"mdy\". Default is \"ymd\", as it is the date format from\n", "the example data file provided.")

**`list("timezone")`**

: list("character string; a time zone in which to import the data to\n", "POSIXct format. Default is \"UTC\". Note about time zone: it is\n", "recommended to use the time zone \"UTC\" to avoid any issue\n", "related to summer time and winter time changes.")

**`list("save")`**

: list("logical; if ", list("save = TRUE"), ", saves the file as an .RData file\n", "in a RData folder in the current working directory. If\n", list("save = FALSE"), ", returns the file in the Console, or load in\n", "the Environment if assigned to an object.")

**`list("keep_all")`**

: list("logical; if ", list("keep_all = TRUE"), ", keep all columns from the raw\n", "file. The default is ", list("keep_all = FALSE"), ", and columns that\n", "are not necessary for gas flux calculation are removed.")

**`list("prec")`**

: list("numerical vector; the precision of the instrument for each gas,\n", "in the following order: \"CO2dry_ppm\", \"COdry_ppb\", \"CH4dry_ppb\",\n", "\"N2Odry_ppb\", \"NH3dry_ppb\" and \"H2O_ppm\". The default is\n", list("prec = c(1.6, 23, 13, 2, 23, 33)"), ".")

## Value


 A data frame containing raw data from the Gasmet GT5000 gas analyzer.


## Details


 In  list("date.format") , the date format refers to a date found in the raw data
 file, not the date format in the file name. For the instrument GT5000, the
 date is found in the column "Date".
 
 Note that this function was designed for the following units in the raw file:
 list("\n", "  ", list(), " ppm for ", list(list("html"), list(list("CO2")), list(list(list("CO[2]"), list("ASCII")))), ",\n", "  CO, ", list(list("html"), list(list("CH4")), list(list(list("CH[4]"), list("ASCII")))), ",\n", "  ", list(list("html"), list(list("N2O")), list(list(list("N[2]O"), list("ASCII")))), " and\n", "  ", list(list("html"), list(list("NH3")), list(list(list("NH[3]"), list("ASCII")))), "\n", "  ", list(), " vol-% for ", list(list("html"), 
    list(list("H2O")), list(list(list("H[2]O"), list("ASCII")))), "\n", "  ", list(), " mbar for pressure\n", "  ", list(), " Celsius for temperature") 
 If your Gasmet GT5000 uses different units, either convert the units after
 import, change the settings on your instrument, or contact the maintainer of
 this package for support.
 
 The precision of the instrument is needed to restrict kappa-max
 ( list(list("k.max")) ) in the non-linear flux calculation
 ( list(list("HM.flux")) ). Kappa-max is inversely proportional to
 instrument precision. If the precision of your instrument is unknown, it is
 better to use a low value (e.g. 1 ppm for
 list(list("html"), list(list("CO2")), list(list(list("CO[2]"), list("ASCII"))))  and
 list(list("html"), list(list("H2O")), list(list(list("H[2]O"), list("ASCII")))) , or 1 ppb for
 list(list("html"), list(list("CH4")), list(list(list("CH[4]"), list("ASCII")))) , CO
 list(list("html"), list(list("N2O")), list(list(list("N[2]O"), list("ASCII"))))  and
 list(list("html"), list(list("NH3")), list(list(list("NH[3]"), list("ASCII")))) ) to allow for more
 curvature, especially for water vapor fluxes, or very long measurements, that
 are normally curved. The default values given for instrument precision are
 the ones provided by the manufacturer upon request, for the latest model of
 this instrument available at the time of the creation of this function (08-2024).


## Examples

```r


# Load file from downloaded package

file.path <- system.file("extdata", "GT5000/GT5000.TXT", package = "goFlux")



# Run function

imp.GT5000 <- import.GT5000(inputfile = file.path)

```

## See Also


 Use the wrapper function  list(list("import2RData")) 
          to import multiple files from the same folder path using any instrument.
 
 See also, import functions for other instruments:
           list(list("import.DX4015")) ,
           list(list("import.EGM5")) ,
           list(list("import.G2201i")) ,
           list(list("import.G2508")) ,
           list(list("import.G4301")) ,
           list(list("import.GAIA")) ,
           list(list("import.GasmetPD")) ,
           list(list("import.LI6400")) ,
           list(list("import.LI7810")) ,
           list(list("import.LI7820")) ,
           list(list("import.LI8100")) ,
           list(list("import.LI8200")) ,
           list(list("import.LI8250")) ,
           list(list("import.N2OM1")) ,
           list(list("import.N2Oi2")) ,
           list(list("import.uCH4")) ,
           list(list("import.uN2O")) ,
           list(list("import.UGGA")) 
 
 See  list(list("timezones"))  for a description of the underlying
          timezone attribute.


