---
title: "`import.uCH4`"
code-block-bg: true
---


 Imports single raw gas measurement files from the MIRA Ultra
 list(list("html"), list(list("CH<sub>4</sub>")), list(list(list("CH[4]"), list("ASCII")))) /
 list(list("html"), list(list("C<sub>2</sub>H<sub>6</sub>")), list(list(list("C[2]H[6]"), list("ASCII")))) 
 Natural Gas Leak Detection System (with GPS) from Aeris Technologies
 ( list(list("html"), list(list("CH<sub>4</sub>")), list(list(list("CH[4]"), list("ASCII")))) ,
 list(list("html"), list(list("C<sub>2</sub>H<sub>6</sub>")), list(list(list("C[2]H[6]"), list("ASCII"))))  and
 list(list("html"), list(list("H<sub>2</sub>O")), list(list(list("H[2]O"), list("ASCII")))) ) with the extension .txt


## Description

Import function for the MIRA Ultra
 list(list("html"), list(list("CH<sub>4</sub>")), list(list(list("CH[4]"), list("ASCII")))) /
 list(list("html"), list(list("C<sub>2</sub>H<sub>6</sub>")), list(list(list("C[2]H[6]"), list("ASCII"))))  analyzer
 from Aeris Technologies

## Usage

```r


import.uCH4(

  inputfile,

  date.format = "mdy",

  timezone = "UTC",

  save = FALSE,

  keep_all = FALSE,

  prec = c(1, 0.5, 15)

)

```

## Arguments

| Argument | Description |
|:---------|:------------|
| `inputfile` | character string; the name of a file with the extension .txt |
| `date.format` | character string; specifies the date format found in the raw data file. Choose one of the following: "dmy", "ymd", or "mdy". Default is "mdy", as it i... |
| `timezone` | character string; a time zone in which to import the data to POSIXct format. Default is "UTC". Note about time zone: it is recommended to use the time... |
| `save` | logical; if save = TRUE , saves the file as an .RData file in a RData folder in the current working directory. If save = FALSE , returns the file in t... |
| `keep_all` | logical; if keep_all = TRUE , keep all columns from the raw file. The default is keep_all = FALSE , and columns that are not necessary for gas flux ca... |
| `prec` | numerical vector; the precision of the instrument for each gas, in the following order: "CH4_ppb", "C2H6dry_ppb" and "H2O_ppm". The default is prec = ... |

## Details


 In  list("date.format") , the date format refers to a date found in the raw data
 file, not the date format in the file name. For these instruments, the date
 is found in the column "Time Stamp".
 
 Note that this function was designed for the following units in the raw file:
 list("\n", "  ", list(), " ppm for ", list(list("html"), list(list("CH4")), list(list(list("CH[4]"), list("ASCII")))), " and\n", "  ", list(list("html"), list(list("H2O")), list(list(list("H[2]O"), list("ASCII")))), "\n", "  ", list(), " ppb for ", list(list("html"), list(list("C2H6")), list(list(list("C[2]H[6]"), list("ASCII")))), "\n", "  ", list(), " mbars for pressure\n", "  ", list(), " Celsius for temperature") 
 If your Aeris instrument (MIRA Ultra
 list(list("html"), list(list("CH4")), list(list(list("CH[4]"), list("ASCII")))) /
 list(list("html"), list(list("C2H6")), list(list(list("C[2]H[6]"), list("ASCII"))))  analyzer) uses
 different units, either convert the units after import, change the settings
 on your instrument, or contact the maintainer of this package for support.
 
 The precision of the instrument is needed to restrict kappa-max
 ( list(list("k.max")) ) in the non-linear flux calculation
 ( list(list("HM.flux")) ). Kappa-max is inversely proportional to
 instrument precision. If the precision of your instrument is unknown, it is
 better to use a low value (e.g. 1 ppm for
 list(list("html"), list(list("C2H6")), list(list(list("C[2]H[6]"), list("ASCII"))))  and
 list(list("html"), list(list("CH4")), list(list(list("CH[4]"), list("ASCII")))) , or 1 ppb for
 list(list("html"), list(list("H2O")), list(list(list("H[2]O"), list("ASCII")))) ) to allow for more
 curvature, especially for water vapor fluxes, or very long measurements, that
 are normally curved. The default values given for instrument precision are
 the ones found  list(list("https://aerissensors.com/mira-pico-mobile-lds/"), list("online")) 
 for the latest model of this instrument available at the
 time of the creation of this function (01-2024).


## Examples

```r


# Load file from downloaded package

file.path <- system.file("extdata", "uCH4/uCH4.txt", package = "goFlux")



# Run function

imp.uCH4 <- import.uCH4(inputfile = file.path)

```

## See Also


 Use the wrapper function  list(list("import2RData")) 
          to import multiple files from the same folder path using any instrument.
 
 See also, import functions for other instruments:
           list(list("import.DX4015")) ,
           list(list("import.eosMX12")) ,
           list(list("import.EGM5")) ,
           list(list("import.G2201i")) ,
           list(list("import.G2508")) ,
           list(list("import.G4301")) ,
           list(list("import.GAIA")) ,
           list(list("import.GasmetPD")) ,
           list(list("import.GT5000")) ,
           list(list("import.HT8850")) ,
           list(list("import.LI6400")) ,
           list(list("import.LI7810")) ,
           list(list("import.LI7820")) ,
           list(list("import.LI8100")) ,
           list(list("import.LI8150")) ,
           list(list("import.LI8200")) ,
           list(list("import.LI8250")) ,
           list(list("import.N2OM1")) ,
           list(list("import.N2Oi2")) ,
           list(list("import.skyline")) ,
           list(list("import.uN2O")) ,
           list(list("import.UGGA")) 
 
 See  list(list("timezones"))  for a description of the underlying
          timezone attribute.


