---
title: "`import.EGM5`"
code-block-bg: true
---


 Imports single raw gas measurement files from the PP-Systems EGM-5 Portable
 list(list("html"), list(list("CO<sub>2</sub>")), list(list(list("CO[2]"), list("ASCII"))))  Gas Analyzer, with
 the extension .TXT


## Description

Import function for the PP-Systems EGM-5 Portable
 list(list("html"), list(list("CO<sub>2</sub>")), list(list(list("CO[2]"), list("ASCII"))))  Gas Analyzer

## Usage

```r


import.EGM5(

  inputfile,

  date.format = "dmy",

  timezone = "UTC",

  save = FALSE,

  keep_all = FALSE,

  prec = c(3, 1, 500),

  proc.data.field = NULL

)

```

## Arguments

| Argument | Description |
|:---------|:------------|
| `inputfile` | character string; the name of a file with the extension .TXT |
| `date.format` | character string; specifies the date format found in the raw data file. Choose one of the following: "dmy", "ymd", or "mdy". Default is "dmy", as it i... |
| `timezone` | character string; a time zone in which to import the data to POSIXct format. Default is "UTC". Note about time zone: it is recommended to use the time... |
| `save` | logical; if save = TRUE , saves the file as an .RData file in a RData folder in the current working directory. If save = FALSE , returns the file in t... |
| `keep_all` | logical; if keep_all = TRUE , keep all columns from the raw file. The default is keep_all = FALSE , and columns that are not necessary for gas flux ca... |
| `prec` | numerical vector; the precision of the instrument for each gas, in the following order: "CO2dry_ppm", "O2dry_pct" and "H2O_ppm". The default is prec =... |
| `proc.data.field` | numeric value; select the process data field used with the EGM-5. There are 5 different modes available: (1) Measure mode; (2) SRC or Custom mode; (3)... |

## Details


 In  list("date.format") , the date format refers to a date found in the raw data
 file, not the date format in the file name. For the instrument EGM5, the date
 is found in the column "Date".
 
 Note that this function was designed for the following units in the raw file:
 list("\n", "  ", list(), " ppm for ", list(list("html"), list(list("CO2")), list(list(list("CO[2]"), list("ASCII")))), "\n", "  ", list(), " % for ", list(list("html"), list(list("O2")), list(list(list("O[2]"), list("ASCII")))), " (pct)\n", "  ", list(), " mb for ", list(list("html"), list(list("H2O")), list(list(list("H[2]O"), list("ASCII")))), "\n", "  ", list(), " mb for pressure\n", "  ", list(), " Celsius for temperature") 
 If your PP-Systems EGM-5 uses different units, either convert the units after
 import, change the settings on your instrument, or contact the maintainer of
 this package for support.
 
 Note that this instrument measures the "wet" fraction of
 list(list("html"), list(list("CO2")), list(list(list("CO[2]"), list("ASCII"))))  and
 list(list("html"), list(list("O2")), list(list(list("O[2]"), list("ASCII")))) . If water vapor is
 measured, the dry fraction of the gases is calculated automatically. If not,
 it is important to measure the ambient water vapor concentration to convert
 gases into their dry fraction and use those in the following steps of this
 package. For example,  list("CO2dry_ppm = CO2wet_ppm/(1-H2O_ppm/1000000)") .
 
 The precision of the instrument is needed to restrict kappa-max
 ( list(list("k.max")) ) in the non-linear flux calculation
 ( list(list("HM.flux")) ). Kappa-max is inversely proportional to
 instrument precision. If the precision of your instrument is unknown, it is
 better to use a low value (e.g. 1 ppm for
 list(list("html"), list(list("CO2")), list(list(list("CO[2]"), list("ASCII"))))  and
 list(list("html"), list(list("H2O")), list(list(list("H[2]O"), list("ASCII")))) , or 1% for
 list(list("html"), list(list("O2")), list(list(list("O[2]"), list("ASCII")))) ) to allow for more
 curvature, especially for water vapor fluxes, or very long measurements, that
 are normally curved. The default values given for instrument precision are
 the ones provided by the manufacturer upon request, for the latest model of
 this instrument available at the time of the creation of this function (11-2023).
 
 Look up the
 list(list("https://ppsystems.com/download/technical_manuals/80109-1-EGM-5_Operation_V103.pdf"), list("EGM-5 Operation Manual")) 
 at page 90 for more details about the different Process Data Fields
 ( list("proc.data.field") ).
 
 Note that the default file extension for this instrument is .TXT, however,
 it is also possible to use with a .csv file format.


## Examples

```r


# Load file from downloaded package

file.path <- system.file("extdata", "EGM5/EGM5.TXT", package = "goFlux")



# Run function

imp.EGM5 <- import.EGM5(inputfile = file.path)

```

## See Also


 Use the wrapper function  list(list("import2RData")) 
          to import multiple files from the same folder path using any instrument.
 
 See also, import functions for other instruments:
           list(list("import.DX4015")) ,
           list(list("import.eosMX12")) ,
           list(list("import.G2201i")) ,
           list(list("import.G2508")) ,
           list(list("import.G4301")) ,
           list(list("import.GAIA")) ,
           list(list("import.GasmetPD")) ,
           list(list("import.GT5000")) ,
           list(list("import.HT8850")) ,
           list(list("import.LI6400")) ,
           list(list("import.LI7810")) ,
           list(list("import.LI7820")) ,
           list(list("import.LI8100")) ,
           list(list("import.LI8150")) ,
           list(list("import.LI8200")) ,
           list(list("import.LI8250")) ,
           list(list("import.N2OM1")) ,
           list(list("import.N2Oi2")) ,
           list(list("import.skyline")) ,
           list(list("import.uCH4")) ,
           list(list("import.uN2O")) ,
           list(list("import.UGGA")) 
 
 See  list(list("timezones"))  for a description of the underlying
          timezone attribute.


